services:
  - type: web
    name: sistem-ujian
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "30"
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: strict
      - key: FILESYSTEM_DISK
        value: local
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
